"""initial schema

Revision ID: 9c8e7e92b9d5
Revises: 
Create Date: 2026-06-13 08:44:01.905980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8e7e92b9d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='admin', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_admin_users_email')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doi', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('journal_name', sa.String(length=255), nullable=True),
    sa.Column('journal_issn', sa.String(length=32), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('license_type', sa.String(length=100), nullable=True),
    sa.Column('abstract_from_metadata', sa.Text(), nullable=True),
    sa.Column('xml_url', sa.Text(), nullable=True),
    sa.Column('xml_source', sa.String(length=100), nullable=True),
    sa.Column('xml_r2_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='metadata_found', nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi', name='uq_articles_doi')
    )
    op.create_index('ix_articles_field', 'articles', ['field'], unique=False)
    op.create_index('ix_articles_journal_name', 'articles', ['journal_name'], unique=False)
    op.create_index('ix_articles_published_date', 'articles', ['published_date'], unique=False)
    op.create_index('ix_articles_status', 'articles', ['status'], unique=False)
    op.create_table('journals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issn_print', sa.String(length=32), nullable=True),
    sa.Column('issn_online', sa.String(length=32), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='2', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_journals_name')
    )
    op.create_index('ix_journals_active', 'journals', ['active'], unique=False)
    op.create_index('ix_journals_field', 'journals', ['field'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_jobs_created_at', 'pipeline_jobs', ['created_at'], unique=False)
    op.create_index('ix_pipeline_jobs_job_type', 'pipeline_jobs', ['job_type'], unique=False)
    op.create_index('ix_pipeline_jobs_status', 'pipeline_jobs', ['status'], unique=False)
    op.create_table('article_figures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('figure_label', sa.String(length=100), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_r2_key', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_credit', sa.Text(), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_figures_article_id', 'article_figures', ['article_id'], unique=False)
    op.create_table('article_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_sections_article_id', 'article_sections', ['article_id'], unique=False)
    op.create_index('ix_article_sections_section_name', 'article_sections', ['section_name'], unique=False)
    op.create_table('curation_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('public_interest', sa.Integer(), nullable=True),
    sa.Column('novelty', sa.Integer(), nullable=True),
    sa.Column('evidence_strength', sa.Integer(), nullable=True),
    sa.Column('human_relevance', sa.Integer(), nullable=True),
    sa.Column('story_potential', sa.Integer(), nullable=True),
    sa.Column('overhype_risk', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_curation_scores_article_id', 'curation_scores', ['article_id'], unique=False)
    op.create_index('ix_curation_scores_selected', 'curation_scores', ['selected'], unique=False)
    op.create_table('generated_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('plain_title', sa.Text(), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('article_body', sa.Text(), nullable=True),
    sa.Column('difficult_words_json', sa.JSON(), nullable=True),
    sa.Column('mcqs_json', sa.JSON(), nullable=True),
    sa.Column('limitations_json', sa.JSON(), nullable=True),
    sa.Column('source_attribution', sa.Text(), nullable=True),
    sa.Column('fact_check_json', sa.JSON(), nullable=True),
    sa.Column('generation_model', sa.String(length=255), nullable=True),
    sa.Column('review_status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_articles_article_id', 'generated_articles', ['article_id'], unique=False)
    op.create_index('ix_generated_articles_published_at', 'generated_articles', ['published_at'], unique=False)
    op.create_index('ix_generated_articles_review_status', 'generated_articles', ['review_status'], unique=False)
    op.create_table('llm_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('input_tokens_estimate', sa.Integer(), nullable=True),
    sa.Column('output_tokens_estimate', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_runs_article_id', 'llm_runs', ['article_id'], unique=False)
    op.create_index('ix_llm_runs_created_at', 'llm_runs', ['created_at'], unique=False)
    op.create_index('ix_llm_runs_status', 'llm_runs', ['status'], unique=False)
    op.create_index('ix_llm_runs_task_name', 'llm_runs', ['task_name'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('generated_article_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_article_id'], ['generated_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_events_action', 'review_events', ['action'], unique=False)
    op.create_index('ix_review_events_article_id', 'review_events', ['article_id'], unique=False)
    op.create_index('ix_review_events_created_at', 'review_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_events_created_at', table_name='review_events')
    op.drop_index('ix_review_events_article_id', table_name='review_events')
    op.drop_index('ix_review_events_action', table_name='review_events')
    op.drop_table('review_events')
    op.drop_index('ix_llm_runs_task_name', table_name='llm_runs')
    op.drop_index('ix_llm_runs_status', table_name='llm_runs')
    op.drop_index('ix_llm_runs_created_at', table_name='llm_runs')
    op.drop_index('ix_llm_runs_article_id', table_name='llm_runs')
    op.drop_table('llm_runs')
    op.drop_index('ix_generated_articles_review_status', table_name='generated_articles')
    op.drop_index('ix_generated_articles_published_at', table_name='generated_articles')
    op.drop_index('ix_generated_articles_article_id', table_name='generated_articles')
    op.drop_table('generated_articles')
    op.drop_index('ix_curation_scores_selected', table_name='curation_scores')
    op.drop_index('ix_curation_scores_article_id', table_name='curation_scores')
    op.drop_table('curation_scores')
    op.drop_index('ix_article_sections_section_name', table_name='article_sections')
    op.drop_index('ix_article_sections_article_id', table_name='article_sections')
    op.drop_table('article_sections')
    op.drop_index('ix_article_figures_article_id', table_name='article_figures')
    op.drop_table('article_figures')
    op.drop_index('ix_pipeline_jobs_status', table_name='pipeline_jobs')
    op.drop_index('ix_pipeline_jobs_job_type', table_name='pipeline_jobs')
    op.drop_index('ix_pipeline_jobs_created_at', table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index('ix_journals_field', table_name='journals')
    op.drop_index('ix_journals_active', table_name='journals')
    op.drop_table('journals')
    op.drop_index('ix_articles_status', table_name='articles')
    op.drop_index('ix_articles_published_date', table_name='articles')
    op.drop_index('ix_articles_journal_name', table_name='articles')
    op.drop_index('ix_articles_field', table_name='articles')
    op.drop_table('articles')
    op.drop_table('admin_users')
    # ### end Alembic commands ###